add openjdk-21 for MC versions above 1.20.4

diff --git a/mcstart b/mcstart
--- a/mcstart
+++ b/mcstart
@@ -20,52 +20,63 @@ else
   exit 1
 fi
 
+# get CPu architecture for java in Ubuntu
+if [ "$(arch)" = aarch64 ]; then
+  arch=arm64
+else
+  arch=amd64
+fi
+
 # Set variable for each java version needed
 if [[ "$ID" == "ubuntu" ]] || [[ "$ID" == "debian" ]] || [[ "$ID" == "linuxmint" ]]; then
-java8=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
-java17=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
+  java8=/usr/lib/jvm/java-8-openjdk-"$arch"/jre/bin/java
+  java17=/usr/lib/jvm/java-17-openjdk-"$arch"/bin/java
+  java21=/usr/lib/jvm/java-21-openjdk-"$arch"/bin/java
 elif [[ "$ID" == "fedora" ]] || [[ "$ID" == "rhel" ]] || [[ "$ID" == "rocky" ]]; then
-java8=/usr/lib/jvm/jre-1.8.0/bin/java
-java17=/usr/lib/jvm/jre-17/bin/java
+  java8=/usr/lib/jvm/jre-1.8.0/bin/java
+  java17=/usr/lib/jvm/jre-17/bin/java
+  java21=/usr/lib/jvm/jre-21/bin/java
 else
   echo "Untested OS. Please verify and improve this script."
   exit 1
 fi
 
 # Get Minecraft server software and version from first and second CLI options 
-cd $(echo $HOME)
+cd "$HOME" || ( echo "Could not change to $HOME"; exit )
 #echo $PWD
-mcSrvrType=$1 
+mcSrvrType="$1" 
 
 # Check and set input variables if valid selections
-if [[ -e $mcSrvrType/$2 && -d $mcSrvrType/$2 ]];
+if [[ -e "$mcSrvrType"/"$2" && -d "$mcSrvrType"/"$2" ]];
 then
 	echo "Found $mcSrvrType-$2"
-	srvrDir=$HOME/$mcSrvrType/$2
-	linkTarget=$(readlink -f $1/$2)
-	buildVersion=$(basename $linkTarget)
-	gameDir=$2
-elif ! $1;
+	srvrDir="$HOME"/"$mcSrvrType"/"$2"
+	linkTarget=$(readlink -f "$1"/"$2")
+	buildVersion=$(basename "$linkTarget")
+	gameDir="$2"
+elif ! "$1";
 then
 	echo "MC server type not valid at first option"
 	help
-elif ! $2;
+elif ! "$2";
 then
 	echo "MC server version not valid at second option"
 	help
 fi
 
 # Get MC server minor version for java compatibilty
-IFS=. read major minor point <<< $buildVersion
-if [[ $minor < 17 ]];
+IFS=. read major minor point <<< "$buildVersion"
+if [[ "$minor" -lt 17 ]];
 then
-	javabin=$java8
+	javabin="$java8"
+elif [[ "$minor" -ge 20 ]] && [[ "$point" -ge 4 ]]; then
+  javabin="$java21"
 else
-	javabin=$java17
+	javabin="$java17"
 fi
 
 # Get configured port for MC server and echo to console
-srvrPort=$(grep "server-port" $srvrDir/server.properties | awk -F = '{ print $2 }')
+srvrPort=$(grep "server-port" "$srvrDir"/server.properties | awk -F = '{ print $2 }')
 
 # Help/Usage
 
@@ -92,13 +103,13 @@ if [[ ! -x /usr/bin/tmux ]]; then
 fi
 
 # Change to directory selected version is located in. 
-cd $srvrDir
+cd "$srvrDir" || ( echo "Could not change to $srvrDir"; exit )
 #echo $PWD
 
 # Java command to start MC server in a screen session. 
-if [[ $mcSrvrType == forge ]];
+if [[ "$mcSrvrType" == forge ]];
 then
-	echo "Starting $mcSrvrType-$buildVersion on Port: $srvrPort"
+	echo "Starting ${mcSrvrType}-${buildVersion} on Port: $srvrPort"
 	# screen -d -m -S "MCServer_$mcSrvrType-$buildVersion" $srvrDir/run.sh
   # Using tmux now. Starting with Rocky Linux 8 screen was dropped
   tmux new-session -d -s "MCServer_${mcSrvrType}" -n "MCServer_${mcSrvrType}-${buildVersion}" "$srvrDir"/run.sh
