converted to /bin/sh and added distro detection for java paths

diff --git a/mcstart b/mcstart
--- a/mcstart
+++ b/mcstart
@@ -1,4 +1,4 @@
-#!/bin/bash 
+#!/bin/sh 
 
 # Enable debugging
 #set -x
@@ -6,11 +6,24 @@
 
 # Declare variables
 
+# get distro from /etc/os-release
+if [ -e /etc/os-release ]; then
+	. /etc/os-release
+	dist=$ID
+fi
+
 # Set variable for each java version needed
-java8=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
-java11=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
-java16=/usr/lib/jvm/java-16-openjdk-amd64/bin/java
-java17=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
+if [ $dist = arch ]; then
+	java8=/usr/lib/jvm/java-8-openjdk/jre/bin/java
+	#java11=/usr/lib/jvm/java-11-openjdk/bin/java
+	#java16=/usr/lib/jvm/java-16-openjdk/bin/java
+	java17=/usr/lib/jvm/java-17-openjdk/bin/java
+else
+	java8=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
+	#java11=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
+	#java16=/usr/lib/jvm/java-16-openjdk-amd64/bin/java
+	java17=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
+fi
 
 # Help/Usage
 
@@ -25,16 +38,15 @@ help()
 }
 
 # Get Minecraft server software and version from first and second CLI options 
-cd $(echo "$HOME")
-#echo $PWD
+cd "$HOME" || echo "I can't change to your home directory"; exit
 
-if [ -z $1 ];
+if [ -z "$1" ];
 then
 	echo "No options set..."
 	help
 	exit 1
 else
-	if [[ -z $2 ]];
+	if [ -z "$2" ];
 	then
 		mcVersion="current"
 	else
@@ -46,43 +58,43 @@ fi
 
 
 # Check and set input variables if valid selections
-if [[ -e $mcSrvrDir && -d $mcSrvrDir ]];
+if [ -e "$mcSrvrDir" ] && [ -d "$mcSrvrDir" ];
 then
 	echo "Found $mcSrvrType/$mcVersion"
 	srvrDir="$HOME"/"$mcSrvrDir"
 	linkTarget=$(readlink -f "$mcSrvrDir")
 	buildVersion=$(basename "$linkTarget")
+	cd "$srvrDir" || echo "Failed to change to MC server directory"; exit
 else
 	echo "MC server type or version not valid."
 	help
 fi
 
 # Get MC server minor version for java compatibilty
-IFS=. read major minor point <<< "$buildVersion"
-if [[ $minor == 17 ]]; then
-	javabin="$java16"
-elif [[ $minor > 17 ]]; then
-	javabin="$java17"
-else
+#IFS=. read major minor point <<< "$buildVersion"
+IFS=.
+set -- "$buildVersion"
+#major=$1
+minor="$2"
+#point=$3
+if [ "$minor" -lt 18 ]; then
 	javabin="$java8"
+else
+	javabin="$java17"
 fi
 
 # Get configured port for MC server and echo to console
 srvrPort=$(grep "server-port" "$srvrDir"/server.properties | awk -F = '{ print $2 }')
 
-# Main program
-
-# Change to directory selected version is located in. 
-cd "$srvrDir"
-#echo $PWD
+## Main program
 
 # Java command to start MC server in a screen session. 
-if [[ $mcSrvrType == forge ]];
+if [ "$mcSrvrType" = forge ];
 then
 	echo "Starting $mcSrvrType-$buildVersion on Port: $srvrPort"
-	screen -d -m -S "MCServer_$mcSrvrType-$buildVersion" /run.sh
+	screen -d -m -S "MCServer_$mcSrvrType-$buildVersion" ./run.sh
 	
-elif [[ $mcSrvrType == fabric ]];
+elif [ "$mcSrvrType" = fabric ];
 then
 	echo "Starting $mcSrvrType-$buildVersion on Port: $srvrPort"
 	screen -d -m -S "MCServer_$mcSrvrType-$buildVersion" "$javabin" -jar "$mcSrvrType"-"$buildVersion"-server-launch.jar
