fixed erroneous exit commands

diff --git a/mcstart b/mcstart
--- a/mcstart
+++ b/mcstart
@@ -3,6 +3,9 @@
 # Enable debugging
 #echo $PWD
 
+#echo "option 1: $1"
+#echo "option 2: $2"
+
 # Declare variables
 
 # get distro from /etc/os-release
@@ -11,17 +14,23 @@ if [ -e /etc/os-release ]; then
 	dist=$ID
 fi
 
+#echo "dist = $dist"
+
 # Set variable for each java version needed
-if [ "$dist" = arch ]; then
+if [ "$dist" = "arch" ]; then
 	java8=/usr/lib/jvm/java-8-openjdk/jre/bin/java
+#	echo "java8 = $java8"
 	#java11=/usr/lib/jvm/java-11-openjdk/bin/java
 	#java16=/usr/lib/jvm/java-16-openjdk/bin/java
 	java17=/usr/lib/jvm/java-17-openjdk/bin/java
+#	echo "java17 = $java17"
 else
 	java8=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
+#	echo "java8 = $java8"
 	#java11=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
 	#java16=/usr/lib/jvm/java-16-openjdk-amd64/bin/java
 	java17=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
+#	echo "java17 = $java17"
 fi
 
 # Help/Usage
@@ -37,7 +46,9 @@ help()
 }
 
 # Get Minecraft server software and version from first and second CLI options 
-cd "$HOME" || echo "I can't change to your home directory"; exit
+cd "$HOME" || echo "I can't change to your home directory"
+
+#echo "HOME = $HOME"
 
 if [ -z "$1" ];
 then
@@ -55,6 +66,8 @@ else
 	mcSrvrDir="$mcSrvrType"/"$mcVersion"
 fi
 
+#echo "mcSrvrType = $mcSrvrType"
+#echo "mcSrvrDir = $mcSrvrDir"
 
 # Check and set input variables if valid selections
 if [ -e "$mcSrvrDir" ] && [ -d "$mcSrvrDir" ];
@@ -63,7 +76,7 @@ then
 	srvrDir="$HOME"/"$mcSrvrDir"
 	linkTarget=$(readlink -f "$mcSrvrDir")
 	buildVersion=$(basename "$linkTarget")
-	cd "$srvrDir" || echo "Failed to change to MC server directory"; exit
+	cd "$srvrDir" || echo "Failed to change to MC server directory"
 else
 	echo "MC server type or version not valid."
 	help
@@ -82,8 +95,13 @@ else
 	javabin="$java17"
 fi
 
+#echo "minor = $minor"
+#echo "javabin = $javabin"
+
 # Get configured port for MC server and echo to console
 srvrPort=$(grep "server-port" "$srvrDir"/server.properties | awk -F = '{ print $2 }')
+
+#echo "srvrPort = $srvrPort"
 
 ## Main program
 
